spring:
# 如果没有aliyun oss 打开这个配置
#  autoconfigure:
#    exclude: cn.javaer.aliyun.spring.boot.autoconfigure.oss.OssAutoConfiguration
  boot:
    admin:
      client:
        url: http://localhost:9002

  # 访问：http://localhost:port/domain/druid/login.html 进行登录访问。
  rabbitmq:
    host: 39.108.191.56
    username: admin
    password: admin
    port: 5672
    
  redis:
    host: 39.108.191.56
    port: 6379
    timeout: 90000
    password: root
      
eureka:
  client: #客户端注册进eureka服务列表内
    service-url:
      #defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
      defaultZone:  http://localhost:5000/eureka  #单机版
  instance:
    # 为注册的这个服务起个别名
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
    prefer-ip-address: true     #使用ip进行注册
    # 注册中心跳转到swagger接口
    status-page-url-path:  /swagger-ui.html
    # #绑定客户端的ip而不是主机号
    hostname: ${spring.cloud.client.ip-address}   # ${spring.cloud.client.ip-address} 参考https://blog.csdn.net/xichenguan/article/details/76632033
    
# 阿里云OSS对象存储，如果没有aliyun oss 注释这个配置
aliyun:
  oss:
    # 确认endpoint里面的请求地址跟bucket是否都一致。 https://mvp.aliyun.com/zhidao/9180
    endpoint: oss-cn-shanghai.aliyuncs.com
    access-key-id: LTAIWAkS6XmKzy7s 
    access-key-secret: '{cipher}AQA1zBHTPSISH0lh0Y3jc+SAOstUgYXdfSyUrnihYWji8cmNSQThR0exfTKY1VAY3CfMUjWC6e5NS7RYbriclET8Nl8jNQbZZlrbbV5n+NBsffsBGbA62HZlqj4AocEpth8QK0kppLITaTio9Av3lhTCQ6w2vzWkYiPloYx7WOLK1JBYp3x4RVOiIXC2a8okPSvOIQTIiRFLblobnnAguI0c7ySoJcw0YWcGaf7mUA6dtZsBChZlQQdFl8K9m9srB9ByITKbaWHVMRpJaMOfOXX+2kzltVBMh1FMHNBXGT1Q+VLCEjbCuj13dOwSw1W1KiFDq8fBdflg6xuu0ZsuZpHoAxAHzxfN2xCIyuwjEm4FiP+bHKtT/ikdtyG7iGOTdJzF9O+8THalmrwLRV+qGn8j'
    

# 监控平台：include: "*"表示 暴露所有端点，info, health... 等等
management:
  endpoints:
    web:
      exposure:
        # * 在YAML中有特殊的含义，所以如果你想包含（或排除）所有的端点，一定要加引号，如下例所示：
        include: "*"
        
