spring:
  servlet:
    # 设置上传文件大小
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
# 如果没有aliyun oss 打开这个配置
#  autoconfigure:
#    exclude: cn.javaer.aliyun.spring.boot.autoconfigure.oss.OssAutoConfiguration
  boot:
    admin:
      client:
        url: http://198.13.55.220:9090
  datasource: # Druid连接池的配置信息
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://rm-wz95iq4b1998037si9o.mysql.rds.aliyuncs.com:3306/youyd?characterEncoding=utf-8&useSSL=false
    type: com.alibaba.druid.pool.DruidDataSource
    username: root1
    password: 123456Qq=
    initialSize: 105 # 池启动时创建的连接数量
    maxWait: 60000 # 配置获取连接等待超时的时间
    minIdle: 105 # 在不新建连接的条件下，池中保持空闲的最少连接数
    maxActive: 1000 # 同一时间可以从池分配的最多连接数量。设置为0时表示无限制。
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000 # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
    validationQuery: SELECT 1 FROM DUAL # 用来检测连接是否有效的sql，要求是一个查询语句，常用select 'x'。如果validationQuery为null，testOnBorrow、testOnReturn、testWhileIdle都不会起作用
    filters: stat,wall # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
    poolPreparedStatements: true # 打开PSCache，并且指定每个连接上PSCache的大小
    maxPoolPreparedStatementPerConnectionSize: 20 # 要启用PSCache，必须配置大于0，当大于0时，poolPreparedStatements自动触发修改为true。
    testOnBorrow: false # 取得连接时是否进行有效性验证（即是否还和数据库连通的）
    testWhileIdle: true # 连接空闲时是否进行有效性验证（即是否还和数据库连通的）
    minEvictableIdleTimeMillis: 300000 # 配置一个连接在池中最小生存的时间，单位是毫秒
    timeBetweenEvictionRunsMillis: 60000 # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
    testOnReturn: false # 返回连接时是否进行有效性验证（即是否还和数据库连通的）

  # 访问：http://39.108.191.56:port/domain/druid/login.html 进行登录访问。
  rabbitmq:
    host: 39.108.191.56
    username: admin
    password: admin
    port: 5672
    
  redis:
    host: 39.108.191.56
    port: 6379
    timeout: 90000
    password: root
      
eureka:
  client: #客户端注册进eureka服务列表内
    service-url:
      #defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
      defaultZone:  http://198.13.55.220:5000/eureka  #单机版
  instance:
    # 为注册的这个服务起个别名
    instance-id: http://198.13.55.220:${server.port}
    prefer-ip-address: true     #使用ip进行注册
    # 注册中心跳转到swagger接口
    status-page-url-path:  /swagger-ui.html
    # #绑定客户端的ip而不是主机号
    hostname: 198.13.55.220   # ${spring.cloud.client.ip-address} 参考https://blog.csdn.net/xichenguan/article/details/76632033
    
# 阿里云OSS对象存储，如果没有aliyun oss 注释这个配置
aliyun:
  oss:
    # 确认endpoint里面的请求地址跟bucket是否都一致。 https://mvp.aliyun.com/zhidao/9180
    endpoint: oss-cn-shanghai.aliyuncs.com
    access-key-id: LTAIWAkS6XmKzy7s 
    access-key-secret: '{cipher}AQA1zBHTPSISH0lh0Y3jc+SAOstUgYXdfSyUrnihYWji8cmNSQThR0exfTKY1VAY3CfMUjWC6e5NS7RYbriclET8Nl8jNQbZZlrbbV5n+NBsffsBGbA62HZlqj4AocEpth8QK0kppLITaTio9Av3lhTCQ6w2vzWkYiPloYx7WOLK1JBYp3x4RVOiIXC2a8okPSvOIQTIiRFLblobnnAguI0c7ySoJcw0YWcGaf7mUA6dtZsBChZlQQdFl8K9m9srB9ByITKbaWHVMRpJaMOfOXX+2kzltVBMh1FMHNBXGT1Q+VLCEjbCuj13dOwSw1W1KiFDq8fBdflg6xuu0ZsuZpHoAxAHzxfN2xCIyuwjEm4FiP+bHKtT/ikdtyG7iGOTdJzF9O+8THalmrwLRV+qGn8j'
    

# 监控平台：include: "*"表示 暴露所有端点，info, health... 等等
management:
  endpoints:
    web:
      exposure:
        # * 在YAML中有特殊的含义，所以如果你想包含（或排除）所有的端点，一定要加引号，如下例所示：
        include: "*"
        

### Hystrix 配置，解决Spring Cloud第一次调用失败
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            # 熔断器超时时间，默认：1秒
            timeoutInMilliseconds: 10000
ribbon:  
  ReadTimeout: 60000  
  ConnectTimeout: 60000  
# 使用HTTP了client rpc调用
feign:
  httpclient:
    enabled: true
# feign请求打印日志
logging:
  level:
    com.youyd.api.user.UserServiceRpc: debug
